package com.mydb.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jiuri.com.dagger2demo.ui.fragment.riji.DateInfo;

import com.mydb.db.DateInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dateInfoDaoConfig;

    private final DateInfoDao dateInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dateInfoDaoConfig = daoConfigMap.get(DateInfoDao.class).clone();
        dateInfoDaoConfig.initIdentityScope(type);

        dateInfoDao = new DateInfoDao(dateInfoDaoConfig, this);

        registerDao(DateInfo.class, dateInfoDao);
    }
    
    public void clear() {
        dateInfoDaoConfig.clearIdentityScope();
    }

    public DateInfoDao getDateInfoDao() {
        return dateInfoDao;
    }

}
